<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Buy\**" />
    <Compile Remove="Finance\**" />
    <Compile Remove="Sale\**" />
    <Compile Remove="Warehouses\**" />
    <EmbeddedResource Remove="Buy\**" />
    <EmbeddedResource Remove="Finance\**" />
    <EmbeddedResource Remove="Sale\**" />
    <EmbeddedResource Remove="Warehouses\**" />
    <None Remove="Buy\**" />
    <None Remove="Finance\**" />
    <None Remove="Sale\**" />
    <None Remove="Warehouses\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Basic\W_CustomerServices.cs" />
    <Compile Remove="Basic\W_GoodsServices.cs" />
    <Compile Remove="Basic\W_SettlementAccountServices.cs" />
    <Compile Remove="Basic\W_SupplierServices.cs" />
    <Compile Remove="Basic\W_WarehoursesServices.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HslCommunication" Version="7.0.1" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.95" />
    <PackageReference Include="RabbitMQ.Client" Version="6.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinformDevFramework.IRepository\WinformDevFramework.IRepository.csproj" />
    <ProjectReference Include="..\WinformDevFramework.IServices\WinformDevFramework.IServices.csproj" />
    <ProjectReference Include="..\WinformDevFramework.Models\WinformDevFramework.Models.csproj" />
    <ProjectReference Include="..\WinformDevFramework.Repository\WinformDevFramework.Repository.csproj" />
  </ItemGroup>

</Project>
